FROM ros:humble
LABEL maintainer="bernd.pfrommer@gmail.com"
LABEL version="1.0"
LABEL description="jammy/humble image with FLIR spinnaker SDK"
ARG DEBIAN_FRONTEND=noninteractive
ARG ROS2_VERSION=humble
#
# FLIR spinnaker information
#
ARG SPINN_VERSION=2.6.0.157
ARG SPINN_OS=Ubuntu20.04
ARG SPINN_ARCH=amd64
RUN apt-get update

# for add-apt-repository and to make debconf happy
RUN apt-get -y install software-properties-common apt-utils

#
# some additional ROS2 packages
#
RUN apt-get -y install python3-osrf-pycommon ros-${ROS2_VERSION}-image-transport ros-${ROS2_VERSION}-cv-bridge ros-${ROS2_VERSION}-sensor-msgs ros-${ROS2_VERSION}-std-msgs ros-${ROS2_VERSION}-rosbag2* ros-${ROS2_VERSION}-tf2-ros ros-${ROS2_VERSION}-image-geometry ros-${ROS2_VERSION}-tf2-geometry-msgs ros-${ROS2_VERSION}-camera-info-manager ros-${ROS2_VERSION}-ament-clang-format ros-${ROS2_VERSION}-ament-cmake-clang-format

# wstool and colcon
RUN apt-get -y install python3-colcon-common-extensions python3-wstool

#
# some additional ubuntu packages:
#
# - git
# - opencv
#
RUN apt-get -y install git libopencv-dev


#
# create and install fake qt5-default package
# Taken from: https://askubuntu.com/questions/1335184/qt5-default-not-in-ubuntu-21-04
#
RUN sudo apt-get install -y equivs
COPY jammy_qt5-default-control.txt /tmp/jammy_qt5-default-control.txt
RUN equivs-build /tmp/jammy_qt5-default-control.txt
RUN apt-get install -y ./qt5-default_5.99.99+fake-13ubuntu37_all.deb

#
# install FLIR Spinnaker SDK from local package
#
#COPY spinnaker-${SPINN_VERSION}-${SPINN_OS}-${SPINN_ARCH}-pkg.tar.gz /tmp/
COPY spinnaker-${SPINN_VERSION}-${SPINN_ARCH} /tmp/spinnaker-${SPINN_VERSION}-${SPINN_ARCH}
# install dependencies
RUN apt-get -y install iputils-ping wget libavcodec58 libavformat58 libswscale5 libswresample3 libavutil56 libusb-1.0-0 libpcre2-16-0 libdouble-conversion3 libxcb-xinput0 libxcb-xinerama0
RUN ls /tmp/
RUN cd /tmp/spinnaker-${SPINN_VERSION}-${SPINN_ARCH} && sh ./install_spinnaker.sh
RUN rm -rf /tmp/spinnaker-${SPINN_VERSION}-${SPINN_ARCH}
