image_width: 1600
image_height: 1200
camera_name: left
distortion_model: plumb_bob
#comentarios considerando outputs Matlab
camera_matrix: # stereoParams.CameraParameters1.IntrinsicMatrix'
  rows: 3
  cols: 3
  data: [1378.9, 0.0, 775.2,
         0.0, 1375.1, 591.1,
         0.0, 0.0, 1.0]
distortion_coefficients: # stereoParams.CameraParameters1.RadialDistortion e stereoParams.CameraParameters1.TangentialDistortion
  rows: 1
  cols: 5
  data: [-0.2057, 0.1535, 0.0, 0.0, 0.0] # [k1, k2, t1, t2, k3]
rectification_matrix: # stereoParams.CameraParameters1.RotationMatrices(:,:,1)'
  rows: 3
  cols: 3
  data: [0.9913, -0.0189, -0.1303,
         0.0183, 0.9998, -0.0060,
         0.1304, 0.0035, 0.9915]
projection_matrix: # Matriz intrinsica e stereoParams.CameraParameters1.TranslationVectors(1,:)
  rows: 3
  cols: 4
  data: [1378.9, 0.0, 775.2, -151.0486,
         0.0, 1375.1, 591.1, -173.8812,
         0.0, 0.0, 1.0, 729.5163]
